# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: xrhoda <xrhoda@student.wethinkcode.co.z    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/12/25 19:56:50 by dwillems          #+#    #+#              #
#    Updated: 2019/10/18 09:12:02 by xrhoda           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT		=	atom
SOURCES		=	src/main.ml
LIBS		=	unix
include OCamlMakefile