# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: xrhoda <xrhoda@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/12/25 19:56:50 by dwillems          #+#    #+#              #
#    Updated: 2019/10/17 06:37:23 by xrhoda           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT		=	atom
SOURCES		=	src/atom.ml src/carbon.ml src/chlorine.ml src/fluorine.ml src/hydrogen.ml src/sodium.ml src/oxygen.ml src/main.ml
LIBS		=	unix
include OCamlMakefile