# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: xrhoda <xrhoda@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/12/25 19:56:50 by dwillems          #+#    #+#              #
#    Updated: 2019/10/11 10:36:25 by xrhoda           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT		=	crypt
SOURCES		=	src/cipher.ml src/uncipher.ml src/main.ml

include OCamlMakefile