# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: xrhoda <xrhoda@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/12/25 19:56:50 by dwillems          #+#    #+#              #
#    Updated: 2019/10/16 07:33:10 by xrhoda           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT		=	people
SOURCES		=	src/people.ml src/doctor.ml src/main.ml
LIBS		=	unix
include OCamlMakefile